name: cloverland_backend

services:
  web:
    container_name: cloverland_backend
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sleep
      - infinity
    ports:
      - ${PORT}:${PORT}
    volumes:
      - type: bind
        source: ./
        target: /code
        bind:
          create_host_path: true
    restart: always
