name: cloverland_backend

services:
  web:
    container_name: cloverland_backend
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - make
      - run
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/code
    restart: always
