name: cloverland_backend

networks:
  cloverland_network:
    external: true

services:
  web:
    container_name: cloverland_backend
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - make
      - run
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      cloverland_network:
        ipv4_address: ${ALLOWED_HOST}
    ports:
      - mode: ingress
        target: ${PORT}
        published: ${PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: ./
        target: /code
        bind:
          create_host_path: true
