import os
from dotenv import load_dotenv

load_dotenv()


DEFAULT_SUPERUSER_FIRST_NAME = os.getenv("DEFAULT_SUPERUSER_FIRST_NAME")
DEFAULT_SUPERUSER_LAST_NAME = os.getenv("DEFAULT_SUPERUSER_LAST_NAME")
DEFAULT_SUPERUSER_EMAIL = os.getenv("DEFAULT_SUPERUSER_LAST_NAME")
DEFAULT_SUPERUSER_PASSWORD = os.getenv("DEFAULT_SUPERUSER_PASSWORD")
DEFAULT_SUPERUSER_USERNAME = os.getenv("DEFAULT_SUPERUSER_USERNAME")

NETWORK_SYMBOL = os.getenv("NETWORK_SYMBOL")
NETWORK_RPC_URL = os.getenv("NETWORK_RPC_URL")
NETWORK_BLOCK_EXPLORER_BASE_URL = os.getenv("NETWORK_BLOCK_EXPLORER_BASE_URL")
NETWORK_NAME = os.getenv("NETWORK_NAME")
NETWORK_UNIT = os.getenv("NETWORK_UNIT")

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
SENGRID_EMAIL_SENDER = os.getenv("SENGRID_EMAIL_SENDER")

APP_BASE_URL = os.getenv("APP_BASE_URL")
ADMIN_BASE_URL = os.getenv("ADMIN_BASE_URL")

MONGODB_URI = os.getenv("MONGODB_URI")
MONGODB_DATABASE_NAME = os.getenv("MONGODB_DATABASE_NAME")

ALLOWED_HOST = os.getenv("ALLOWED_HOST")
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG") == "1"

PORT = os.getenv("PORT")
