# Generated by Django 4.2 on 2023-04-22 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lottery', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128)),
                ('private_key', models.CharField(max_length=128)),
                ('paid', models.BooleanField(default=False)),
                ('transaction_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='lottery.lottery')),
            ],
        ),
    ]
